/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chess;

import java.awt.Graphics;

import theme.ThemeFactory;

/**
 *
 * @author feroze
 */
public class GameSettings extends javax.swing.JFrame {

    /**
     * Creates new form GameSettings
     */
    public GameSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        themeButtonGroup = new javax.swing.ButtonGroup();
        selectTheme = new javax.swing.JLabel();
        classic = new javax.swing.JRadioButton();
        blueBerryPie = new javax.swing.JRadioButton();
        hersheysChoco = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        selectTheme.setText("Select Theme");

        themeButtonGroup.add(classic);
        classic.setText("Classic ");
        classic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classicActionPerformed(evt);
            }
        });

        themeButtonGroup.add(blueBerryPie);
        blueBerryPie.setText("Blue Berry Pie");
        blueBerryPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBerryPieActionPerformed(evt);
            }
        });

        themeButtonGroup.add(hersheysChoco);
        hersheysChoco.setText("Hershey's Choco");
        hersheysChoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hersheysChocoActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(classic)
                                .addGap(18, 18, 18)
                                .addComponent(blueBerryPie)
                                .addGap(18, 18, 18)
                                .addComponent(hersheysChoco))
                            .addComponent(selectTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(selectTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classic)
                    .addComponent(blueBerryPie)
                    .addComponent(hersheysChoco))
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classicActionPerformed
        // TODO add your handling code here:
    	Main.selectedTheme = ThemeFactory.getSharedFThemeFactory().createClassicTheme();
    	Main.selectedTheme.notifyAllObservers();
    	
    }//GEN-LAST:event_classicActionPerformed

    private void blueBerryPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBerryPieActionPerformed
        // TODO add your handling code here:
    	Main.selectedTheme = ThemeFactory.getSharedFThemeFactory().createBlueberryPieTheme();
    	Main.selectedTheme.notifyAllObservers();
    }//GEN-LAST:event_blueBerryPieActionPerformed

    private void hersheysChocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hersheysChocoActionPerformed
        // TODO add your handling code here:
    	Main.selectedTheme = ThemeFactory.getSharedFThemeFactory().createHersheyChocolateTheme();
    	Main.selectedTheme.notifyAllObservers();
    }//GEN-LAST:event_hersheysChocoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void gameSettingsWindow() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSettings().setVisible(true);
            }
        });
        */
        this.setVisible(true);
    }
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton blueBerryPie;
    private javax.swing.JRadioButton classic;
    private javax.swing.JRadioButton hersheysChoco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel selectTheme;
    private javax.swing.ButtonGroup themeButtonGroup;
    // End of variables declaration//GEN-END:variables
}
